version: "2"
services:
  vscode:
    image: vscode-remote-tunnels
    container_name: vscode-remote
    environment:
      - MACHINE_NAME=YOUR_MACHINE_NAME
      - SUDO_PASSWORD=password #optional
    volumes:
      - vscode_data:/data/.vscode-server
      - vscode_cli_data:/data/.vscode
    restart: unless-stopped
    dns:
      - 1.1.1.1
    user: "${UID}:${GID}"  #optionally set this to your user_id:group_id (id username) if running docker with sudo ex: user: 1000:1000
