version: "2"
services:
  vscode:
    image: vscode-remote-tunnels
    container_name: vscode-remote
    environment:
      - MACHINE_NAME=YOUR_MACHINE_NAME
      - SUDO_PASSWORD=password #optional
      - PGID=1000
      - PUID=1000
    volumes:
      # set to the --cli-data-dir 
      - config:/config/
      # User home dir
      - data:/data/
    restart: unless-stopped
    dns:
      - 1.1.1.1
