#!/usr/bin/with-contenv bash

PUID=${PUID:-911}
PGID=${PGID:-911}

groupmod -o -g "$PGID" user
usermod -o -u "$PUID" user


mkdir -p /data/.ssh

if [[ -n "${SUDO_PASSWORD}" ]]; then
    echo "setting up sudo access"
    if ! grep -q 'user' /etc/sudoers; then
        echo "adding user to sudoers"
        echo "user ALL=(ALL:ALL) ALL" >> /etc/sudoers
    fi
    echo "setting sudo password using SUDO_PASSWORD env var"
    echo -e "${SUDO_PASSWORD}\n${SUDO_PASSWORD}" | passwd user
fi

if [[ ! -f /data/.bashrc ]]; then
    cp /root/.bashrc /data/.bashrc
fi

if [[ ! -f /data/.profile ]]; then
    cp /root/.profile /data/.profile
fi


# chown -R user:user /data
chmod 700 /data/.ssh
if [[ -n "$(ls -A /data/.ssh)" ]]; then
    chmod 600 /data/.ssh/*
fi

echo '
───────────────────────────────────────
GID/UID
───────────────────────────────────────'
echo "
User UID:    $(id -u user)
User GID:    $(id -g user)
───────────────────────────────────────
"

lsiown -R user:user /data
lsiown -R user:user /config
