name: Build and publish image - insider
on:
  release:
    types: [published]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        name: Build and publish image job
        steps:
            - name: Checkout master
              uses: actions/checkout@master
            - name: Build and publish image
              uses: ilteoood/docker_buildx@master
              with:
                tag: insider
                platform: linux/amd64,linux/arm64,linux/arm/v7
                imageName: ilteoood/vscode-remote-tunnels
                publish: true
                dockerUser: ilteoood
                dockerPassword: ${{ secrets.DOCKER_HUB_PASSWORD }}
                buildArg: BUILD=insider
